/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package oopseminar2;

import oopseminar2.controller.Controller;
import oopseminar2.data.Teacher;

public class App {
    public static void main(String[] args) {
        Controller controller = new Controller();
        //Создаём юзеров студентов
        //Teacher teacher1 = new Teacher("Vadim", "Kostromin", "Borisovich", 1L);
        controller.createUser("Ivan", "Ivanov", "Andreevich");
        controller.createUser("Dmitriy", "Ivanov", "Konstantinovich");
        controller.createUser("Evgeniy", "Kozlov", "Sergeevich");
        controller.createUser("Denis", "Pantelemonov", "Valeryevich");
        controller.createUser("Artur", "Tumakov", "Pavlovich");
        controller.createUser("Mihail", "Semechenko", "Mihailovich");
        controller.createUser("Anton", "Tyrin", "Valadimirovich");
        controller.createUser("ivan", "Kataev", "Andreevich");
        controller.createUser("Ian", "Shitov", "Andreevich");
        //Выводим на экран всех юзеров студентов
        //controller.getAllUsers();
        //Создание учебной группы
        controller.createStudyGroup(new Teacher("Aleksey", "Hasyangin", "Andreevich", null));
        //Выводим группы на экран
        //controller.getAllStudyGroups();

        controller.getSortedStudens();



    } 
}
